
import { IItemCard } from '../Interfaces'

export const items: IItemCard[] = [
    { name: "nirvana", price: 5.3, img: "https://drive.google.com/uc?id=17581Nizb0jP6XMeay74DlJwFzLvpIcdl" },
    { name: "rammstein", price: 2.1, img: "https://drive.google.com/uc?id=1lB_l7lE12gfiSQQaPx5w8xsxR7nwB0P1" },
    { name: "led zeppelin", price: 5.3, img: "https://drive.google.com/uc?id=1hWQFl3dFBw_8YxhAzzTbwWViIMHJoljB" },
    { name: "nirvana", price: 5.3, img: "https://drive.google.com/uc?id=17581Nizb0jP6XMeay74DlJwFzLvpIcdl" },
    { name: "rammstein", price: 2.1, img: "https://drive.google.com/uc?id=1lB_l7lE12gfiSQQaPx5w8xsxR7nwB0P1" },
    { name: "led zeppelin", price: 5.3, img: "https://drive.google.com/uc?id=1hWQFl3dFBw_8YxhAzzTbwWViIMHJoljB" },
    { name: "nirvana", price: 5.3, img: "https://drive.google.com/uc?id=17581Nizb0jP6XMeay74DlJwFzLvpIcdl" },
    { name: "rammstein", price: 2.1, img: "https://drive.google.com/uc?id=1lB_l7lE12gfiSQQaPx5w8xsxR7nwB0P1" },
    { name: "led zeppelin", price: 5.3, img: "https://drive.google.com/uc?id=1hWQFl3dFBw_8YxhAzzTbwWViIMHJoljB" },
    { name: "nirvana", price: 5.3, img: "https://drive.google.com/uc?id=17581Nizb0jP6XMeay74DlJwFzLvpIcdl" },
    { name: "rammstein", price: 2.1, img: "https://drive.google.com/uc?id=1lB_l7lE12gfiSQQaPx5w8xsxR7nwB0P1" },
    { name: "led zeppelin", price: 5.3, img: "https://drive.google.com/uc?id=1hWQFl3dFBw_8YxhAzzTbwWViIMHJoljB" },
    { name: "nirvana", price: 5.3, img: "https://drive.google.com/uc?id=17581Nizb0jP6XMeay74DlJwFzLvpIcdl" },
    { name: "rammstein", price: 2.1, img: "https://drive.google.com/uc?id=1lB_l7lE12gfiSQQaPx5w8xsxR7nwB0P1" },
    { name: "led zeppelin", price: 5.3, img: "https://drive.google.com/uc?id=1hWQFl3dFBw_8YxhAzzTbwWViIMHJoljB" },
    { name: "rammstein", price: 2.1, img: "https://drive.google.com/uc?id=1lB_l7lE12gfiSQQaPx5w8xsxR7nwB0P1" },
    { name: "led zeppelin", price: 5.3, img: "https://drive.google.com/uc?id=1hWQFl3dFBw_8YxhAzzTbwWViIMHJoljB" },
    { name: "nirvana", price: 5.3, img: "https://drive.google.com/uc?id=17581Nizb0jP6XMeay74DlJwFzLvpIcdl" },
    { name: "rammstein", price: 2.1, img: "https://drive.google.com/uc?id=1lB_l7lE12gfiSQQaPx5w8xsxR7nwB0P1" },
    { name: "led zeppelin", price: 5.3, img: "https://drive.google.com/uc?id=1hWQFl3dFBw_8YxhAzzTbwWViIMHJoljB" },
    { name: "nirvana", price: 5.3, img: "https://drive.google.com/uc?id=17581Nizb0jP6XMeay74DlJwFzLvpIcdl" },
    { name: "rammstein", price: 2.1, img: "https://drive.google.com/uc?id=1lB_l7lE12gfiSQQaPx5w8xsxR7nwB0P1" },
    { name: "led zeppelin", price: 5.3, img: "https://drive.google.com/uc?id=1hWQFl3dFBw_8YxhAzzTbwWViIMHJoljB" },
    { name: "rammstein", price: 2.1, img: "https://drive.google.com/uc?id=1lB_l7lE12gfiSQQaPx5w8xsxR7nwB0P1" },
    { name: "led zeppelin", price: 5.3, img: "https://drive.google.com/uc?id=1hWQFl3dFBw_8YxhAzzTbwWViIMHJoljB" },
    { name: "nirvana", price: 5.3, img: "https://drive.google.com/uc?id=17581Nizb0jP6XMeay74DlJwFzLvpIcdl" },
    { name: "rammstein", price: 2.1, img: "https://drive.google.com/uc?id=1lB_l7lE12gfiSQQaPx5w8xsxR7nwB0P1" },
    { name: "led zeppelin", price: 5.3, img: "https://drive.google.com/uc?id=1hWQFl3dFBw_8YxhAzzTbwWViIMHJoljB" },
    { name: "nirvana", price: 5.3, img: "https://drive.google.com/uc?id=17581Nizb0jP6XMeay74DlJwFzLvpIcdl" },
    { name: "rammstein", price: 2.1, img: "https://drive.google.com/uc?id=1lB_l7lE12gfiSQQaPx5w8xsxR7nwB0P1" },
    { name: "led zeppelin", price: 5.3, img: "https://drive.google.com/uc?id=1hWQFl3dFBw_8YxhAzzTbwWViIMHJoljB" },
]